name: @name@
version: @version@
description: A Minecraft Plugin addon designed to create in-game trend screens while hooking with Ecoporium
author: yakovliam
website: https://yakovliam.com
main: com.yakovliam.ecoporiumscreenaddon.EcoporiumScreenAddonPlugin
api-version: 1.17
depend:
  - Ecoporium
  - PlaceholderAPI
  - Vault